# Generated by Django 5.1.4 on 2024-12-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.CharField(default='vendor', max_length=255),
        ),
    ]
