# Generated by Django 5.1.4 on 2024-12-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=355)),
                ('image', models.ImageField(upload_to='sourcing_products/')),
                ('description', models.TextField()),
            ],
        ),
    ]
