# Generated by Django 5.1.4 on 2024-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_sourcingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingProductRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('image', models.ImageField(upload_to='sourcing_products/')),
                ('description', models.TextField()),
                ('added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SourcingProduct',
        ),
    ]
