# Generated by Django 5.1.4 on 2024-12-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_sourcingproductrequest_delete_sourcingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingproductrequest',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
