# Generated by Django 5.1.4 on 2025-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_sourcingproductrequest_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
